amadeus4dev/amadeus-java

README.md, gradle.properties, src/main/java/com/amadeus/ReferenceData.java, src/main/java/com/amadeus/referenceData/Airlines.java, src/main/java/com/amadeus/resources/AirTraffic.java, src/main/java/com/amadeus/resources/Airline.java, src/main/java/com/amadeus/resources/Location.java, src/main/java/com/amadeus/resources/Period.java, src/main/java/com/amadeus/travel/analytics/AirTraffic.java, src/main/java/com/amadeus/travel/analytics/airTraffic/Booked.java, src/main/java/com/amadeus/travel/analytics/airTraffic/BusiestPeriod.java, src/test/java/com/amadeus/AmadeusTest.java, src/test/java/com/amadeus/NamespaceTest.java
Add endpoint implementations for the new following APIs:
Airline Code LookUp
Flight Busiest Traveling Period
Flight Most Booked Destinations
=> Add endpoint implementations for the new APIs

README.md, src/main/java/com/amadeus/Amadeus.java, src/main/java/com/amadeus/Configuration.java
Replaced client_id and client_secret by API_KEY and API_SECRET
Fixed typos and updated examples to be aligned with our portal + other SDKs
=> Update authentication documentation and examples

.travis.yml, README.md, src/main/java/com/amadeus/Amadeus.java, src/main/java/com/amadeus/HTTPClient.java, src/main/java/com/amadeus/Request.java, src/main/java/com/amadeus/client/AccessToken.java, src/main/java/com/amadeus/resources/FlightOffer.java, src/main/java/com/amadeus/shopping/FlightOffers.java, src/main/java/com/amadeus/shopping/flightOffers/Prediction.java, src/test/java/com/amadeus/AccessTokenTest.java, src/test/java/com/amadeus/HTTPClientTest.java, src/test/java/com/amadeus/NamespaceTest.java, src/test/java/com/amadeus/RequestTest.java
PR updated. This is the final version
=> ADD Flight Choice Prediction + fix POST

README.md, gradle.properties, src/main/java/com/amadeus/Amadeus.java, src/main/java/com/amadeus/Request.java, src/main/java/com/amadeus/resources/FlightOfferSearch.java, src/main/java/com/amadeus/shopping/FlightOffersSearch.java, src/test/java/com/amadeus/AmadeusTest.java, src/test/java/com/amadeus/NamespaceTest.java, src/test/java/com/amadeus/RequestTest.java
FlightOffersSearch updated to support the `POST` verb.
`Content-Type` of the request updated (with unit-tests).
=> Add support for Flight Offers Search POST

README.md, src/main/java/com/amadeus/HTTPClient.java, src/main/java/com/amadeus/resources/FlightPrice.java, src/main/java/com/amadeus/shopping/FlightOffersSearch.java, src/main/java/com/amadeus/shopping/flightOffers/Pricing.java, src/test/java/com/amadeus/NamespaceTest.java
#27 Add flight offer price support api
=> Flight offer price api

README.md, src/main/java/com/amadeus/Constants.java, src/main/java/com/amadeus/HTTPClient.java, src/main/java/com/amadeus/booking/FlightOrder.java, src/test/java/com/amadeus/HTTPClientTest.java, src/test/java/com/amadeus/NamespaceTest.java
=> Add DELETE support for Flight Order Management

README.md, src/main/java/com/amadeus/referenceData/Locations.java, src/main/java/com/amadeus/referenceData/locations/PointOfInterest.java, src/main/java/com/amadeus/resources/PointOfInterest.java, src/test/java/com/amadeus/NamespaceTest.java
=> Add support for Points of Interest retrieve 

src/main/java/com/amadeus/resources/HotelBooking.java
Update `AssociatedRecords` field to `AssociatedRecords[]` in resources of HotelBooking
=> update associatedRecords in hotelBooking model

src/examples/flight/createorders/FlightCreateOrders.java, src/examples/flight/offers/FlightOffersPrice.java, src/main/java/com/amadeus/booking/FlightOrders.java, src/main/java/com/amadeus/resources/FlightOfferSearch.java, src/main/java/com/amadeus/resources/Resource.java, src/main/java/com/amadeus/shopping/flightOffers/Pricing.java
Fix Flight Offers Price and Flight Create Orders implementation and examples
=> Fix the implementation of Flight booking API

README.md, src/main/java/com/amadeus/Amadeus.java, src/main/java/com/amadeus/Safety.java, src/main/java/com/amadeus/resources/SafePlace.java, src/main/java/com/amadeus/safety/SafetyRatedLocation.java, src/main/java/com/amadeus/safety/SafetyRatedLocations.java, src/main/java/com/amadeus/safety/safetyRatedLocations/BySquare.java, src/test/java/com/amadeus/NamespaceTest.java
I don't know why we can't see the Travis on the PR apart from the first commit, but this is the last [Travis build](https://travis-ci.org/github/amadeus4dev/amadeus-java/builds/693936740) which has passed.
=> Add support for safe place API

src/main/java/com/amadeus/resources/SafePlace.java
=> fix bug in safe place model

src/main/java/com/amadeus/resources/FlightOfferSearch.java
Fixes https://github.com/amadeus4dev/amadeus-java/issues/114
=> Fix flight offer resource 

src/main/java/com/amadeus/resources/Traveler.java
Add gender and email address 
https://github.com/amadeus4dev/amadeus-java/issues/117
https://github.com/amadeus4dev/amadeus-java/issues/118
=> Update traveler model

README.md, src/main/java/com/amadeus/Amadeus.java, src/main/java/com/amadeus/DutyOfCare.java, src/main/java/com/amadeus/dutyOfCare/Diseases.java, src/main/java/com/amadeus/dutyOfCare/diseases/Covid19AreaReport.java, src/main/java/com/amadeus/dutyOfCare/diseases/TravelRestrictions.java, src/main/java/com/amadeus/resources/DiseaseAreaReport.java, src/test/java/com/amadeus/NamespaceTest.java
Fixes #103 
@gimperial @tsolakoua 
This PR is ready for review, please go ahead and thank you!
=> Add support for Travel Restrictions API

README.md, src/main/java/com/amadeus/Amadeus.java, src/main/java/com/amadeus/Location.java, src/main/java/com/amadeus/dutyOfCare/Diseases.java, src/main/java/com/amadeus/location/Analytics.java, src/main/java/com/amadeus/location/analytics/CategoryRatedAreas.java, src/main/java/com/amadeus/resources/ScoredLocation.java, src/main/java/com/amadeus/shopping/Availability.java, src/test/java/com/amadeus/NamespaceTest.java
Fixes #102 
Fixes some typos on Javadoc
@gimperial @tsolakoua 
This PR is ready for review, please go ahead and thank you!
=> Add support for Location Score and Fix Javadoc typo

README.md, src/main/java/com/amadeus/Constants.java, src/main/java/com/amadeus/resources/FlightOfferSearch.java, src/main/java/com/amadeus/shopping/FlightOffers.java, src/main/java/com/amadeus/shopping/flightOffers/Upselling.java, src/test/java/com/amadeus/NamespaceTest.java
Fixes #100 
This PR is ready for review, please go ahead and thank you!
=> Add support for Branded Fares Upsell API

src/main/java/com/amadeus/shopping/flightOffers/Upselling.java
=> fix wrong return type at upselling class

src/test/java/com/amadeus/AmadeusTest.java
Fixing the Unit Tests for the constructor.
=> Fixing one Amadeus constructor test

src/main/java/com/amadeus/resources/SeatMap.java
add usbType into the powerAmenity for matching the SeatMap V1.9 update and fix original typo
Fixes #156
=> add usbType for matching the SeatMap V1.9 update

README.md, src/main/java/com/amadeus/referenceData/Locations.java, src/main/java/com/amadeus/referenceData/locations/Hotels.java, src/main/java/com/amadeus/referenceData/locations/hotels/ByCity.java, src/main/java/com/amadeus/referenceData/locations/hotels/ByGeocode.java, src/main/java/com/amadeus/referenceData/locations/hotels/ByHotels.java, src/main/java/com/amadeus/resources/Hotel.java, src/test/java/com/amadeus/NamespaceTest.java, src/test/java/com/amadeus/referenceData/locations/hotels/ByCityIT.java, src/test/java/com/amadeus/referenceData/locations/hotels/ByGeocodeIT.java, src/test/java/com/amadeus/referenceData/locations/hotels/ByHotelsIT.java, src/test/resources/__files/hotels_by_city_response_ok.json, src/test/resources/__files/hotels_by_geocode_response_ok.json, src/test/resources/__files/hotels_by_hotels_response_ok.json
=> Add support for hotel list endpoints

README.md, src/main/java/com/amadeus/Shopping.java, src/main/java/com/amadeus/resources/HotelOfferSearch.java, src/main/java/com/amadeus/shopping/HotelOfferSearch.java, src/main/java/com/amadeus/shopping/HotelOffersSearch.java, src/test/java/com/amadeus/NamespaceTest.java, src/test/java/com/amadeus/shopping/HotelOfferSearchIT.java, src/test/java/com/amadeus/shopping/HotelOffersSearchIT.java, src/test/resources/__files/hotel_offer_search_response_ok.json, src/test/resources/__files/hotel_offers_search_response_ok.json
=> Add support for Hotel Search v3 and keep v2

src/main/java/com/amadeus/resources/HotelOffer.java
=> add email attribute to HotelOffer.HotelContact resource class

README.md, src/main/java/com/amadeus/referenceData/Locations.java, src/main/java/com/amadeus/referenceData/locations/Cities.java, src/main/java/com/amadeus/resources/City.java, src/test/java/com/amadeus/NamespaceTest.java, src/test/java/com/amadeus/referenceData/locations/CitiesIT.java, src/test/resources/__files/city_search_response_ok.json
=> add support for city search

build.gradle
=> Upgrading GSON depenency to fix the CVE

README.md, src/main/java/com/amadeus/Airline.java, src/main/java/com/amadeus/Amadeus.java, src/main/java/com/amadeus/airline/Destinations.java, src/main/java/com/amadeus/resources/Destination.java, src/test/java/com/amadeus/NamespaceTest.java, src/test/java/com/amadeus/airline/DestinationsIT.java, src/test/resources/__files/airline_routes_response_ok.json, src/test/resources/__files/airline_routes_response_ok2.json
Fixes #176
* Added support for [Airport Routes API](https://developers.amadeus.com/self-service/category/air/api-doc/airline-routes)
* Added relevant tests and docs
=> Add Support of Airline Routes V1.0

CHANGELOG.md, README.md, gradle.properties, src/main/java/com/amadeus/Amadeus.java, src/test/java/com/amadeus/AmadeusTest.java
this PR just updates the version-related data, but it doesn't generate the updated Javadocs
=> release 6.2.0

src/main/java/com/amadeus/resources/FlightOfferSearch.java
fix property ```type``` name in ```resources.FlightOfferSearch.Price.AdditionalService```
=> fix property name

src/main/java/com/amadeus/HTTPClient.java
Fixes #
Remove this if you have done all of these:
* Ensure all tests pass and linting
* Add any changes to the README
* Add any changes or new comments to SDK methods
* Ensure this PR only changes what it is intended to change
=> removed superfluous toString on a String

README.md, src/main/java/com/amadeus/dutyOfCare/Diseases.java, src/main/java/com/amadeus/dutyOfCare/diseases/Covid19Report.java, src/main/java/com/amadeus/resources/DiseaseReport.java, src/test/java/com/amadeus/NamespaceTest.java, src/test/java/com/amadeus/dutyOfCare/diseases/Covid19ReportIT.java, src/test/resources/__files/travel_restrictions_v2_response_ok.json
Fixes #187 
- ResourceModel => `src/main/java/com/amadeus/resources/DiseaseReport.java`
- Endpoint => `src/main/java/com/amadeus/dutyOfCare/diseases/Covid19Report.java`
- NamespaceTest => `src/test/java/com/amadeus/NamespaceTest.java`
- IT => `src/test/java/com/amadeus/dutyOfCare/diseases/Covid19ReportIT.java`
=> add support for travel restrictions V2

src/main/java/com/amadeus/Constants.java, src/main/java/com/amadeus/Request.java
- Fix ArrayList Init
- Replace == with .equals for String comparison
=> Fix Sonarcloud warnings for bugs

src/main/java/com/amadeus/HTTPClient.java, src/test/java/com/amadeus/HTTPClientTest.java
Pagination was not properly working because the code assumed the page offset in the URL was always the last which is not the case. Changed to extract exact the code page offset from the URL.
=> Fix pagination and tests

build.gradle
=> Upgrade compilation to java 8

src/main/java/com/amadeus/travel/TripParser.java
=> Import base64 encoder from java.util

src/main/java/com/amadeus/HTTPClient.java
https://github.com/amadeus4dev/amadeus-java/issues/224
=> Remove NullPointerException

src/test/java/com/amadeus/AmadeusTest.java
=> update AmadeusTest tests

src/main/java/com/amadeus/Params.java
=> Log error in catch

src/main/java/com/amadeus/safety/SafetyRatedLocation.java
=> Remove fully qualified name

src/main/java/com/amadeus/resources/Hotel.java, src/main/java/com/amadeus/resources/HotelOfferSearch.java
Fixes #249 
1. Remove `@SerializedName` for `lastUpdate`.
2. Add missing fields `type`, `latitude` and `longitude` for `HotelOfferSearch.Hotel`.
=> Fix: Hotel Resource Models
